<a href="https://colab.research.google.com/github/jzzy-jeff/github-slideshow/blob/master/tensor_quickie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist. load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.4903872 , -0.2179988 ,  0.16803873,  0.59400105, -0.01106219,
         0.08941436, -0.14831011,  0.28040928, -0.06108239, -0.5310488 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.05999217, 0.07877553, 0.11588982, 0.17743462, 0.09688638,
        0.10712705, 0.0844611 , 0.12967229, 0.09215932, 0.05760172]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.2337399

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4927 - accuracy: 0.8555
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1526 - accuracy: 0.9549
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1110 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0861 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0761 - accuracy: 0.9756


In [12]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0782 - accuracy: 0.9743


[0.07815766334533691, 0.9743000268936157]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.15956719e-08, 4.56917881e-08, 3.30229450e-05, 1.55665458e-03,
        1.76691817e-09, 7.83179712e-06, 1.10270998e-13, 9.98382807e-01,
        1.02278354e-05, 9.36245306e-06],
       [5.92781796e-11, 8.37790481e-07, 9.99994874e-01, 1.12292162e-06,
        2.85515412e-20, 3.16731735e-06, 4.53285720e-09, 3.07773466e-15,
        2.24604761e-08, 8.84180636e-16],
       [2.66503179e-07, 9.99521017e-01, 2.85291626e-05, 4.17070987e-05,
        9.95266691e-06, 8.30124827e-06, 1.19897168e-05, 3.32269614e-04,
        4.47791208e-05, 1.07391259e-06],
       [9.99835372e-01, 3.27437438e-10, 1.48336068e-04, 6.23028829e-09,
        7.85583865e-09, 6.45025864e-07, 1.07899859e-05, 4.66261190e-06,
        2.05784598e-08, 7.03060508e-08],
       [1.29189884e-05, 1.29762812e-09, 7.66510220e-06, 6.05655316e-07,
        9.95910168e-01, 3.70054750e-06, 1.51728655e-05, 8.41437868e-05,
        1.42964846e-05, 3.95138236e-03]], dtype=float32)>